---
- name: Clone a repo with separate git directory
  git:
    repo: "{{repo}}"
    dest: "{{dest}}"
    clone: yes
    version: back
    update: yes
    force: true

- name: Update APT
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
- name: Install java
  apt:
    name: openjdk-8-jre-headless
    state: present

- name: install maven (and other packages if needed)
  become: true
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven

- name: maven clean package
  command: mvn -f {{dest}}/DistriBack/pom.xml clean package

- name: "create systemd service"
  template:
    src: "etc/systemd/system/systemd.service.j2"
    dest: "/etc/systemd/system/{{ systemd_service[item].service_name | default(item) }}.service"
    mode: 0664
  with_items: "{{ systemd_service | list }}"
  notify:
    - restart service
  tags:
    - systemd-service

- name: "enable service"
  systemd:
    name: "{{ systemd_service[item].service_name | default(item)  }}.service"
    enabled: "{{ systemd_service[item].enabled | default(False) }}"
  with_items: "{{ systemd_service | list }}"
  tags:
    - systemd-service
  
#- name: Copy file
#  copy: src={{dest}}/DistriBack/target/DistriBack-0.0.1-SNAPSHOT.war dest=/usr/share/tomcat/webapps/DistriBack-0.0.1-SNAPSHOT.war
#  become: true
#  become_user: root
